### PR TITLE
+ Moved outerFocusChangeListener check outside the floatingLabelEnabled ...

### PR DESCRIPTION
**Pull request by sfreeman28**
...check so a focus listener can be added without having to set a label.

### CODE REVIEW

**Comment by sfreeman28** [comment]
This fixes a bug that caused the outerFocusChangeListener not to be called.

The current logic only calls the outerFocusChangeListener when a label has been set.

For my use case I need to set my own focusChangeListener but I don't want a label.

**Comment by cypressious** [comment]
This issue kinda breaks my application. Can we get this merged?

**Comment by rengwuxian** [comment]
Sorry for the late reply. Busy on some other work these days, and have no time on this Library. I'll review this pull request and merge it in several hours.

**Comment by cypressious** [comment]
Thanks, very kind of you. Sorry, if my reply sounded harsh.

**Comment by cypressious** [comment]
Could you please publish the new version to Maven? Thanks.

**Pull request merged**
