### PR TITLE
Removing limitation that was blocking the background customization

### PR DESCRIPTION
**Pull request by lalbuquerque**
I just made a few change to don't block the _9-patch_ customization of EditText. 
The user only have to pass a drawable with the states reference to it (using **android**:_background_="@drawable/edit_text_background") and the work is done.

Ps.: I also added an example to the sample module, showing a sample customization.

### CODE REVIEW

**Comment by rengwuxian** [comment]
Hi @lalbuquerque ,

Thanks for your contribution! But I'm afraid I can't merge this PR. It looks just having added the `android:background` support, which will introduce a new issue: developers will have to set `android:background="@null"` to prevent the framework's EditText background shown. Actually, that's why I haven't added the `android:background` support.

**Comment by lalbuquerque** [comment]
Hey @rengwuxian.

thanks for your reply. As you can see in the example I added, to pass a custom background you have to set `app:met_hideUnderline="true"` and then set the custom background.
If the developer don't want to use any custom background he gotta do nothing because in the code I moved the code `if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
          setBackground(null);
      } else {
          setBackgroundDrawable(null);
      }` to right before the drawing of the underline.
A proof of it is that I didn't change any of the others examples in your **sample** app and they worked perfectly well.

**Comment by rengwuxian** [comment]
Sorry for the long period of disappearance. I'm back to MaterialEditText!

Well, I think we'd better not call `setBackground()` in `onDraw()`. even though duplicates of `setBackground(null)` doesn't bring more performance costs, it makes the code harder to to understand.

**Comment by TCQQ** [comment]
this change has bug, will be: "app:met_hideUnderline" this attributes invalid

**Pull request closed without merging**
