### PR TITLE
Clear Button and Floating Label Corrections

### PR DESCRIPTION
**Pull request by gtcompscientist**
* Clear Button is hidden when there is no text to clear, and is properly initialized when the View is created.
* Floating Label is now shown properly when the text is set programmatically before the View is displayed.
* Icon Left/Right can now be set from Drawable directly, will still apply stateful styling.

### CODE REVIEW

**Comment by rengwuxian** [comment]
Thanks for your help, @gtcompscientist !

At first, sorry for the delayed reply. I've read your code, and there's something worth discussing about:

1. I'm considering to hide clear button for now, because it looks useless. So let's not worry about the solution about the "close button" (I don't think it's a good name^_^) now.
2. I tried to but didn't understand "Floating Label is now shown properly when the text is set programmatically before the View is displayed." that you mentioned. Could you please let me know how it works not properly with the existing code?

Thanks!

**Comment by gtcompscientist** [comment]
@rengwuxian No worries on the timing.
1) Please don't remove the Clear button. It's actually really useful, and something I was planning to add.
2) If you set the floating label to be shown normally (not always) and set the text to a value that should show the floating label before the first time draw() is called, then it gets out of sync with the state of the text/floating label and you get unusual side effects of when it decides to show/not show.

**Comment by rengwuxian** [comment]
I'm just going to remove the "close button" (the icon showing at the right end when there's no text in the EditText). That means, there will be an "X" icon in the right end only when the EditText is not empty.

And about the proper displaying, I still don't get it. I set the text programmatically and the floating label and the clear button worked fine. Did I do something wrong?

**Comment by gtcompscientist** [comment]
Let me see if I can create a sample app that quickly demonstrates the problem I see.

**Comment by rengwuxian** [comment]
Sure! It helps a lot if you leave a sample app here.

**Comment by gtcompscientist** [comment]
Well... in a test app I can't quickly recreate it, so I'll have to dig a little deeper as to what was happening.

**Comment by gtcompscientist** [comment]
Got it! Here's the simplest example I could create. The basics are that you need an edit text, and at ANY point you set the text to null (triggering a hidden NRE in the Text Watcher) and then it's out of sync.

```xml
<?xml version="1.0" encoding="utf-8"?>
<com.rengwuxian.materialedittext.MaterialEditText
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_margin="8dp"
    android:imeOptions="actionNext"
    android:singleLine="true"
    android:textSize="14sp"
    app:met_floatingLabel="normal"/>
```

```java
MaterialEditText nextEditor = (MaterialEditText) this.inflateView(R.layout.basic_edit, parentView, false);
nextEditor.setFloatingLabelText("Test Floating Label");
nextEditor.setHint("Test Hint");
nextEditor.setText("...");
nextEditor.setText(null);
nextEditor.setText("...");
parentView.addView(nextEditor);
```

**Comment by gtcompscientist** [comment]
The more I look at the code-behind and such, the more I think it's a timing issue with the text listeners. Before you merge this, I'll see if I can't figure out a safer way to guarantee the correctness of the label visibility.

**Comment by gtcompscientist** [comment]
Found the underlying cause. A timing issue with the LabelAnimator would get it stuck in the wrong position occasionally. Now it's much safer.

**Comment by rengwuxian** [comment]
After tested on your code and checked the existing code, I found the issue -- it's caused by an incorrect use of ObjectAnimator.reverse(). My fault. Thanks, @gtcompscientist . I've already fixed this floating label bug and pushed it in to github repo.

For the `setIcon...()` functionality, I'll pick the related code and make a specific commit. It's a good enhancement.

**Comment by gtcompscientist** [comment]
Great! Happy to help out where I can.

**Comment by rengwuxian** [comment]
:+1:

**Pull request closed without merging**
